### ISSUE TITLE
麻烦删除 iOS-private-api-checker

### ISSUE THREAD

**Issue by hustcc** [bigrpg/joyengine#1]
iOS-private-api-checker 项目之前由我开源，后来由于版本问题，删除，请麻烦不要上传到github上，感谢。

这个项目现在也麻烦删除一下~

**Comment by bigrpg** [comment]
没问题，我已经删除了！

在2016年05月09 13时00分, "hustcc"notifications@github.com写道:

iOS-private-api-checker 项目之前由我开源，后来由于版本问题，删除，请麻烦不要上传到github上，感谢。

这个项目现在也麻烦删除一下~

**Comment by hustcc** [comment]
非常感谢，代码自己可以保留使用。请不要在网络上传播，感谢配合~~~^-^~
